name: Deploy Website

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Build Website
        run: |
          npm install
          npm install -g gh-pages
          npm run build
          cd out 
          echo 'txphotography.us' > CNAME
          touch .nojekyll
          cd ..
          gh-pages -d out -t true
